# Generated by Django 5.2.17 on 2026-09-15 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=40)),
                ('tenant_phone', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('待确认', '待确认'), ('已生效', '已生效'), ('已终止', '已终止'), ('已取消', '已取消')], default='待确认', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='properties.property')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_end_date', models.DateField()),
                ('planned_days', models.PositiveIntegerField()),
                ('actual_days', models.PositiveIntegerField()),
                ('rent_paid', models.DecimalField(decimal_places=2, help_text='已付租金（按原租期预付）', max_digits=12)),
                ('rent_due', models.DecimalField(decimal_places=2, help_text='按实际租期应付租金', max_digits=12)),
                ('unsettled_rent', models.DecimalField(decimal_places=2, help_text='未结租金（欠付）', max_digits=12)),
                ('rent_refund', models.DecimalField(decimal_places=2, help_text='多付应退租金', max_digits=12)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_refund', models.DecimalField(decimal_places=2, help_text='应退押金', max_digits=12)),
                ('total_refund', models.DecimalField(decimal_places=2, help_text='应退总额', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='contract.contract')),
            ],
        ),
    ]
