# Generated by Django 5.2.17 on 2026-09-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
        ('properties', '0002_seed_properties'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('status', '已生效')), fields=('property',), name='unique_active_contract_per_property'),
        ),
    ]
