# 房源状态
HOUSE_STATUS_PENDING = '待出租'
HOUSE_STATUS_BOOKED = '已预约'
HOUSE_STATUS_SIGNED = '已签约'
HOUSE_STATUS = (HOUSE_STATUS_PENDING, HOUSE_STATUS_BOOKED, HOUSE_STATUS_SIGNED)

# 合同状态
CONTRACT_STATUS_PENDING = '待确认'
CONTRACT_STATUS_ACTIVE = '已生效'
CONTRACT_STATUS_TERMINATED = '已终止'
CONTRACT_STATUS_CANCELLED = '已取消'
CONTRACT_STATUS = (
    CONTRACT_STATUS_PENDING,
    CONTRACT_STATUS_ACTIVE,
    CONTRACT_STATUS_TERMINATED,
    CONTRACT_STATUS_CANCELLED,
)

REPAIR_TYPES = ('水电', '门锁', '管道', '家电', '其他')
USER_ROLES = ('房东', '租客', '物业人员')
