# 业务错误码与提示信息，统一由异常处理器返回给前端
ERROR_CODES = {
    'PROPERTY_NOT_FOUND': 'PROPERTY_NOT_FOUND',
    'BOOKING_CONFLICT': 'BOOKING_CONFLICT',
    'REPAIR_INVALID': 'REPAIR_INVALID',
    'CONTRACT_NOT_FOUND': 'CONTRACT_NOT_FOUND',
    'CONTRACT_INVALID_DATE': 'CONTRACT_INVALID_DATE',
    'CONTRACT_LEASE_OVERLAP': 'CONTRACT_LEASE_OVERLAP',
    'CONTRACT_DUPLICATE': 'CONTRACT_DUPLICATE',
    'CONTRACT_STATUS_INVALID': 'CONTRACT_STATUS_INVALID',
    'CONTRACT_ALREADY_TERMINATED': 'CONTRACT_ALREADY_TERMINATED',
    'SETTLEMENT_NOT_FOUND': 'SETTLEMENT_NOT_FOUND',
    'VALIDATION_ERROR': 'VALIDATION_ERROR',
}

ERROR_MESSAGES = {
    'PROPERTY_NOT_FOUND': '房源不存在',
    'CONTRACT_NOT_FOUND': '合同不存在',
    'CONTRACT_INVALID_DATE': '日期无效',
    'CONTRACT_LEASE_OVERLAP': '同一房源租期重叠',
    'CONTRACT_DUPLICATE': '该房源已签约，不能重复签署',
    'CONTRACT_STATUS_INVALID': '当前合同状态不允许该操作',
    'CONTRACT_ALREADY_TERMINATED': '合同已终止，不能重复操作',
    'SETTLEMENT_NOT_FOUND': '结算单不存在',
    'VALIDATION_ERROR': '参数校验失败',
}
